<?php

namespace HomeBundle\Repository;

/**
 * cacaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cacaRepository extends \Doctrine\ORM\EntityRepository
{
}
